services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
      - ./kids_recordings:/app/kids_recordings
      - /var/run/docker.sock:/var/run/docker.sock  # 👈 🚀 給予 Flask 呼叫 docker run 的通行證！
      - shared-data:/app/uploads
    extra_hosts:
      - "host.docker.internal:host-gateway"

    # 2. 全新的 Python 自動化分析後端
  backend-wer:
    build: ./backend-wer
    ports:
      - "8000:8000"
    volumes:
      - ./models:/root/.cache/whisper

  backend-npvi:   
    image: speech-api:v1  # 🚀【核心更換】：換成組員給的新網站映像檔名字
    container_name: backend-npvi-1
    restart: always
    ports:
      - "8000:8000"  # 💡【Port 錯開】：把同學網站內部的 8000 對應到外部的 8001，防範跟 WER 衝突
    environment:
      - TZ=Asia/Taipei
    # 💡 既然它已經是常駐網站了，原本為了強行喚醒而掛載的 /var/run/docker.sock 與 shared-data 都可以拔掉了，保持乾淨！
    volumes:
      - D:\AI_ENpractice\kids_recordings:/app/data
volumes:
  shared-data: